### PR TITLE
Directory Reorg

### PR DESCRIPTION
**Pull request by rdodev**
* Reorganized each service into its own proper submodule …
* Most of the "trickery" is in package.json since npm doesn't do binary directory hierarchies
* It should be a lot easier to add new services independent of the others

@rosskukulinski let's talk about merging this before adding more services.

### CODE REVIEW

**Comment by rosskukulinski** [comment]
@rdodev trying to find time to review this later this afternoon

**Comment by rosskukulinski** [comment]
(Thanks again for your work!)

@rdodev overall, this is a +1.  My only qualm is the heat template changes that snuck in.  If you yank that, I'll merge.

On a similar tangent, I'm thinking we should make the naming scheme consistent (image-list vs list-zone, vs 'list' vs get-containers) and also cleanup helpers.js.  Usually in node land when you see require('../../../../blah') its an anti-pattern.

**Comment by rdodev** [comment]
Cool. I'll fix that. As for naming consistency, which one sounds more apt
or natural to you? I don't have a strong opinion either way.

On Tuesday, January 20, 2015, Ross Kukulinski <notifications@github.com>
wrote:

> (Thanks again for your work!)
>
> @rdodev <https://github.com/rdodev> overall, this is a +1. My only qualm
> is the heat template changes that snuck in. If you yank that, I'll merge.
>
> On a similar tangent, I'm thinking we should make the naming scheme
> consistent (image-list vs list-zone, vs 'list' vs get-containers) and also
> cleanup helpers.js. Usually in node land when you see
> require('../../../../blah') its an anti-pattern.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pkgcloud/pkgcloud-cli/pull/25#issuecomment-70614387>.
>


-- 
Sent from Gmail Mobile

**Comment by rosskukulinski** [comment]
I wrote a separate ticket so I didn't forget (#26) but I think I prefer list-zones... but pkgcloud lib uses get-zones.

**Comment by rdodev** [comment]
OK, then. Let me remove the orchestration references and commit.

**Comment by rdodev** [comment]
@rosskukulinski done.

**Pull request merged**
