### PR TITLE
Support for Openstack networking : ports

### PR DESCRIPTION
**Pull request by Phanatic**
Adds support for 
port-list
port-create
port-destroy

### CODE REVIEW

**Comment by Phanatic** [comment]
Will fix these now.

**Comment by rosskukulinski** [comment]
sorry @Phanatic for not being on top of these PRs :frowning:

**Comment by Phanatic** [comment]
@rosskukulinski, this PR is now merged with the latest master.

**Comment by rosskukulinski** [comment]
@Phanatic thanks

**Pull request merged**
